# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
before_install:
    - pip install -U pipenv
    - pipenv install --dev
install: skip
script:
    - nox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: stbraun
  password:
      secure: Dr1gjXEvygCgsF7LZ9oNzJY9x+Dwta4QUlQzYvyLTbreGe/U0TC0HF3snygUISFh8sZQyrm+o3vDubpCQIXfF7vhiN4LciYckr2kvAQA7PZ6mInE4HNaOz5/HteqmgqWXi7SNoX5+5r7FfroKlGlt74MgvDH6LubkaFIVnE9IexMySADwk6uRjMJhb0ZyV2Avh4Nsxb6imQPe3Op9oe1MqLQ5kJ3ZGEEC984qA6kcTmXCo8pHq6hi/hdwOwimtUWLyh9Wx4yvkX2xAZJtrNz+pplrSrdZDK+cMyX15AwkM9x2q9bb3pby2C537tx9PzHryjQjWNU6DZFMpXJp88rOx0yoR0h/PCpI3YdcK1YkgkHh0xTCXL6tVyGKu2s0jqW9pKINRG02nCs0TIrhqgPQCkqFw8LiwfPsHHvbwiz1XrNbOoeaUdBeEmAEcDh8rd6ETRX2LQVHKGtcoADgDrT2EWllYZg9a47Pst8rUkgaUuDKzoa4sTANRnLSBo6reIjNreymJVqTK+rg/VPFDWwGz5fXS1NaMMMY+/1ltiZZkw/CCNmTQpLP5YhFjEU6/Kie21tLj+eT5JnUglJKk8yvc/foOMKrHdAbUqN54UVESNToi0HZA3MBtbfopy8CRXMOwUcnwiQCum4Jqx6ywTz2GvW2UOxYmyyo9nm+hqW+wk=
  on:
    tags: true
    repo: stbraun/loganalysis
    python: 3.8
